### PR TITLE
Native App for HRM

### PR DESCRIPTION
**Pull request by greysquidcat**
Cool app you've pioneered.
I'm glad to contribute!
:smile:

This is version 1.0.1

Since you already have a Samsung account I thought maybe you would like to publish the app.

Please share any ideas.

I can provide a video demo of the app if you want.

### CODE REVIEW

**Comment by greysquidcat** [comment]
https://youtu.be/J10rxrjG974

**Comment by loic2665** [comment]
I'm just amazed haha, I don't know wat to say, I will try the app on my watch and I will try to publish it ASAP. I don't know if I have to make an update for this app or create a whole new one. What do you think ?

**Comment by greysquidcat** [comment]
@loic2665 No you've done great work.

I didn't beautify my code unfortunately. It's a bit terse.
If you have any questions about what I've done with the code, go right ahead and ask.
I would recommend keeping both apps.
Not all devices will work with API 3.0.
Does it cost money to put a new app in the Samsung store?

**Comment by loic2665** [comment]
Well to be honest I'm still discovering the code, well it costs nothing to posts it, but it's sure you will have credits for this. :)
So we will keep the web and native version. ^^

**Comment by a93h** [comment]
In case you have any questions. I transferred all my work to this account. I consolidated my accounts.

**Pull request merged**
